project:
  type: book
  output-dir: docs

execute:
  # freeze: auto
  eval: true
  echo: true
  warning: false
  message: false
  # cache: true

book:
  title: "Optimizing Shiny apps"
  subtitle: "A hands-on guide to extract maximum performance"
  author: "G. Vituri"
  date: "3/12/2025"
  page-navigation: true
  reader-mode: true
  
  page-footer:
    left: |
      Text here
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  
  chapters:
    - index.qmd
    - intro.qmd
    - part: part-levels.qmd
      chapters:
      - whale-intro.qmd
      - whale-simple.qmd
      - whale-profiling.qmd
      - whale-reactive-graph.qmd
      - whale-cache.qmd
      - whale-async.qmd
      - whale-backend.qmd
      - whale-languages.qmd
    - part: part-data.qmd
    - part: part-cloud.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

biblio-style: apalike
link-citations: true
links-as-notes: true

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    toc-depth: 3
    toc-expand: true
    bibliography: sources.bib
    highlight-style: github
    page-layout: full
    code-link: true
    callout-appearance: simple
    mermaid:
      theme: forest

  pdf: default